### ISSUE TITLE
切换 my-yesplaymusic-bin 的电子版本到 electron25

### ISSUE THREAD

**Issue by mokurin000** [zxp19821005/My_AUR_Files#13]
另外，该包无需和 yesplaymusic 系冲突，因为可执行文件，资源文件都没有冲突，只有 MPRIS Identity 冲突

**Comment by zxp19821005** [comment]
配置文件是冲突的，在`~/.config`目录，都是`yesplaymusic`.另，electron的版本是由上游开发者来决定的，对方如果使用`electron13`来编译，那么运行的时候就最好使用`electron13`
